### ISSUE TITLE
Create a function to check which claim a user has

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/clean-the-world#10]
### Goal: Use the Firebase Admin SDK to Check a User's Claims

**Branch Name:** `check-claims-function`

### What You Have To Do
- Look into the Firebase Admin SDK Custom Claims [here](https://firebase.google.com/docs/auth/admin/custom-claims)
- Refactor the `create-user` function to give all users created with it the 'data-entry' claim 
- Create a function in `users/firebase-functions.ts` that takes in a user id and checks what claim that user has. Either have it return a boolean value based on whether or not a user has the 'data-entry' claim or return any other piece of data representing that the claim has been checked. This part doen't really matter too much, as we'll be modifying it later to account for multiple different claims (admin, super admin, etc.).
- Once again, [Here](https://console.firebase.google.com/u/0/project/clean-the-world-50a0c/overview) is a link to the Firebase dashboard for ease of access

### Task Tracker:
- [x] Create branch
- [x] Read documentation above
- [x] Refactor create user function
- [x] Create function to check user claims
- [x] Test that function with a route
- [x] Create a PR!
