### ISSUE TITLE
Create a function to push a document to Mongo

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/clean-the-world#12]
### Goal: Create a function and route to push a document to Mongo

**Branch Name:** `post-data-function`

### What You Have To Do
- We will configure Mongo so you have access in subteam
- Create a function that takes in a JSON object and pushes it as a document to our database on MongoDB
- **Note**: the function itself should be able to take any object in JSON structure, but no structure in particular. This is because we have not finalized the necessary data yet. As of right now, for testing purposes, you guys can use this as an example:
![image](https://user-images.githubusercontent.com/52248400/225435908-c0d5a455-962a-4273-855f-4316141bc9e7.png)
- Create a route that calls the function and test it out!

### Task Tracker:
- [x] Create branch
- [x] Make sure you have access to MongoDB
- [ ] Create function to push data
- [ ] Call that function in a route to test
- [ ] Create a PR
