### ISSUE TITLE
Create data entry component

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/clean-the-world#13]
### Goal: Create a component for users to enter data!

**Branch Name:** `data-entry-component`

### What You Have To Do
- Create a data entry component:
- For now, that's just going to be 5 text boxes (with labels) for the following data-types (excluding ID, that's auto generated):
![image](https://user-images.githubusercontent.com/52248400/225458308-c96a26bf-c601-422f-8aa4-e7b7724f9095.png)
- Create a submission button that displays the entered data in some way (as an alert if you want)!

### Task Tracker:
- [x] Create branch
- [x] Create data entry component
- [x] Create submission button
- [x] Test your component
- [x] Create a PR!
