### ISSUE TITLE
Create data entry confirmation page

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/clean-the-world#15]
### Goal: Create a confirmation page for data entry!

**Branch Name:** `data-entry-confirmation`

### What You Have To Do
- Refactor your current data entry component to look a little like the [midfis](https://www.figma.com/file/BqMIEjWt9GYD3xWgCFasof/CTW?node-id=123-2&t=yiUMeFcpTeZujhP9-0)
- Alter the component upon clicking the submission button such that data is no longer editable + replace 'New Entry' with 'Are you sure this is correct?'
- Have the submission button on the confirmation display the data in an alert

### Task Tracker:
- [x] Create branch
- [x] Refactor data entry component
- [x] Create confirmation variant
- [x] Test your component
- [x] Create a PR!
