### ISSUE TITLE
Create a submission popup

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/clean-the-world#16]
### Goal: Create a data entry submission popup!

**Branch Name:** `submission-popup`

### What You Have To Do
- Create a new component titled `submission-popup` with prop 'on-press'
- The component should contain two parts: a confirmation modal and a button that calls the modal
- Create the button such that on a press, it both calls 'on-press' and pulls up the modal
- Create the modal in the style of the design on the far right of the [midfis](https://www.figma.com/file/BqMIEjWt9GYD3xWgCFasof/CTW?node-id=123-2&t=yiUMeFcpTeZujhP9-0)
- Note: styling is not too too important, since these are only midfis. 

### Task Tracker:
- [x] Create branch
- [x] Create button portion of componant
- [x] Create modal portion of component
- [x] Combine the two
- [x] Test it out
- [x] Create a PR!
