### ISSUE TITLE
Create Time Scale Dropdown Component

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/clean-the-world#21]
### Goal: Create a time scale dropdown component that allows users to change the time scale of displayed data!

**Branch Name:** `time-dropdown-component`

### What You Have To Do
- Create a dropdown component that looks like the one in figma: 
<img width="148" alt="image" src="https://user-images.githubusercontent.com/52248400/231574947-c5c3650e-7aee-4883-b987-55816895e6c8.png">
- The options for the dropdown should be Day, Month, and Year
- The dropdown should store the current option as a state within it, the default being Day

### Task Tracker:
- [x] Create branch
- [x] Create dropdown component
- [x] Store the current displayed option as a state
- [x] Test your component
- [x] Create a PR!
