### ISSUE TITLE
Create a past entry card component

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/clean-the-world#22]
### Goal: Create a time scale dropdown component that allows users to change the time scale of displayed data!

**Branch Name:** `past-entry-card`

### What You Have To Do
- Create a card component that represents a past entry, as shown in the figma: 
<img width="423" alt="image" src="https://user-images.githubusercontent.com/52248400/231575440-809257a0-a06f-497e-b389-daf15ddf7202.png">
- The card should be the collapsed state by default (shown in the 3rd and 4th cards) and expand when tapped (shown in the 1st and 2nd card)
- The card should take all shown values as props and stack nicely when put into a container

### Task Tracker:
- [ ] Create branch
- [ ] Create card component as outlined above
- [ ] Create a container for multiple cards have them stack nicely
- [ ] Test your component
- [ ] Create a PR!
