### ISSUE TITLE
Horizontal Scrolling List Component

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/clean-the-world#25]
### Goal: Create a Horizontal Scrolling List Component

**Branch Name:** `horizontal-scrolling-list`

### What You Have To Do
- Create a component that allows a user to scroll through a list of entries by clicking left or right arrows. This one's a bit tricky to explain, but seeing it on the figma should help you understand a bit better:

<img width="212" alt="image" src="https://user-images.githubusercontent.com/52248400/233196117-82f8f2bd-1a02-49d9-aea5-4cc267504db2.png">

- It should take in a list of entries as a prop, each one containing a header and a value collected
- The user should be able to navigate the list cyclicly, meaning clicking right on the last entry should display the first entry, and vice versa 

### Task Tracker:
- [ ] Create branch
- [ ] Create horizontal scrolling component
- [ ] Ensure props and wraparound function as specified
- [ ] Test your component
- [ ] Create a PR!
