### ISSUE TITLE
Monthly/Yearly Data Visualization Page

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/clean-the-world#27]
### Goal: Create a Month/Year card component as seen in the midfis

**Branch Name:** `viz-page`

### What You Have To Do
- Create a historical monthly/yearly data visualization page, as seen in the following designs:
<img width="653" alt="image" src="https://user-images.githubusercontent.com/52248400/233193084-85b4a3b0-8f6e-4d53-8c4f-1e5d39151561.png">

The page should be styled as in the midfis above, however, some important things to keep in mind:

**Do not worry about the graph!** For now, just use a placeholder image. 

Make sure the page takes in just about everything as a prop. This includes:
- Whether the page is representing a month or a year (as a bool)
- Fog net ID
- Total water collected in that time period
- A list of all entries that month/year. For a month, this would be individual entries. For a year, this would be total water collected each month

### Task Tracker:
- [ ] Create branch
- [ ] Create page as outlined above and in the Figma
- [ ] Utilize props to make page flexible and adaptable
- [ ] Test your page
- [ ] Create a PR!
