### ISSUE TITLE
Create Month and Year Cards

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/clean-the-world#28]
### Goal: Create a Month/Year card component as seen in the midfis

**Branch Name:** `month-year-card`

### What You Have To Do
- Create a card component that represents a month or year during which data was collected in the past, as seen in the following designs:
<img width="274" alt="image" src="https://user-images.githubusercontent.com/52248400/233190866-f1da53dc-aa15-4bb4-8a2f-04adf8ba606f.png">
<img width="270" alt="image" src="https://user-images.githubusercontent.com/52248400/233190907-23a56abc-d255-48bd-ba64-08d0cd246656.png">
- The card should essentially be a fancy button that takes in month and year / just year (depending on the card type) and routes to a different page (for now, route to `data-entry`)
- The cards should stack nicely when put into a container

### Task Tracker:
- [ ] Create branch
- [ ] Create card component as outlined above
- [ ] Create a container for multiple cards have them stack nicely
- [ ] Test your component
- [ ] Create a PR!
