### ISSUE TITLE
Finalize Data Entry Flow

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/clean-the-world#29]
### Goal: Create a final data entry flow

**Branch Name:** `final-data-entry-flow`

### What You Have To Do
- Using the data entry component and authentication flow, Create the following flow as seen in Figma:
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/52248400/233211184-54645aa2-7956-40ee-8d25-d2a45c6414a2.png">
- Style the components as shown in the Figma to get them looking as close as possible to the designs
- Create a dummy page with dummy text that the user is sent to after confirmation -- there will eventually be a page that says something along the lines of "Today's entry logged," but we haven't quite gotten those designs done
- Ignore the bar at the bottom for this week

### Task Tracker:
- [x] Create branch
- [x] Use existing components to create the data entry flow
- [x] Create dummy page and route to it from confirmation
- [x] Test your implementation
- [x] Create a PR!
