### ISSUE TITLE
Implement Slide Animation on Data Entry Flow

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/clean-the-world#34]
### Goal: Implement a sliding animation in the data entry flow

**Branch Name:** `slide-animation`

### What You Have To Do
- Refactor the current data-entry flow to utilize a modal structure
- Implement sliding transitions between pages
- [Here is a guide](https://itnext.io/change-react-native-screen-animation-direction-with-react-navigation-8cec0f66f22)

### Task Tracker:
- [ ] Create branch
- [ ] Refactor data entry page
- [ ] Implement sliding transitions
- [ ] Test it out
- [ ] Create a PR!
