### ISSUE TITLE
Implement Phone Number Verification

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/clean-the-world#7]
### Goal: Look into and implement Firebase phone number authentication

**Branch Name:** `phone-authentication`

### What you have to do:
- Read the guide [here](https://firebase.google.com/docs/auth/web/phone-auth?authuser=0&hl=en). Note: step 1 is already done for you!
- Create a basic but functional captcha component utilizing the reCAPTCHA widget snippet in the guide above
- Use a basic text input field for step 4 -- we don't need this to be pretty, just want it functioning!
- Complete the flow of phone number verification and have an alert pop up upon completion
- Test your implementation with either fake phone numbers (see guide) or your own!

### Task Tracker:
- [x] Create Branch
- [x] Read and understand linked guide
- [x] Implement reCAPTCHA component
- [x] Create functional text input field
- [x] Complete phone number authentication flow
- [x] Test functionality
- [x] Create a PR!
