### ISSUE TITLE
Create Function for Adding Users

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/clean-the-world#8]
### Goal: Use the Firebase Admin SDK to Add Users

**Branch Name:** `create-user-function`

### What You Have To Do
- Look into the Firebase Admin SDK [here](https://firebase.google.com/docs/auth/admin)
- The eventual goal is to create a POST method route that creates a user given ONLY their phone number, as shown [here](https://firebase.google.com/docs/auth/admin/manage-users#create_a_user). For now, you'll be creating a helper function for that.
- Create a function in `functions.ts` that takes in a phone number and uses that to create a user with Firebase Auth
- [Here](https://console.firebase.google.com/u/0/project/clean-the-world-50a0c/overview) is a link to the Firebase dashboard. You'll see new users under the Authentication tab.

### Task Tracker:
- [x] Create branch
- [x] Read documentation above
- [x] Create a function to create user
- [x] Test your function
- [x] Create a PR!

**Comment by jfeuerstein** [comment]
Nice work guys!
